In [9]:
arr = [1, 0, 2, 3, 2, 0, 0, 4, 5, 1]
i = arr.index(0)
for j in range(i, len(arr)):
    if arr[j] != 0:
        arr[i], arr[j] = arr[j], arr[i]
        i += 1
arr

[1, 2, 3, 2, 4, 5, 1, 0, 0, 0]

In [13]:
from typing import List


def nextGreaterPermutation(A: List[int]) -> List[int]:
    n = len(A)  # size of the array.

    # Step 1: Find the break point:
    ind = -1  # break point
    for i in range(n - 2, -1, -1):
        if A[i] < A[i + 1]:
            # index i is the break point
            ind = i
            break

    # If break point does not exist:
    if ind == -1:
        # reverse the whole array:
        A.reverse()
        return A

    # Step 2: Find the next greater element
    #         and swap it with arr[ind]:
    for i in range(n - 1, ind, -1):
        if A[i] > A[ind]:
            A[i], A[ind] = A[ind], A[i]
            break
    print(A, ind)
    # Step 3: reverse the right half:
    A[ind + 1 :] = reversed(A[ind + 1 :])

    return A


if __name__ == "__main__":
    A = [1, 2, 3]
    ans = nextGreaterPermutation(A)

    print("The next permutation is: [", end="")
    for it in ans:
        print(it, end=" ")
    print("]")

[1, 3, 2] 1
The next permutation is: [1 3 2 ]


In [3]:
def searchInsert(arr: [int], x: int) -> int:
    n = len(arr)  # size of the array
    low = 0
    high = n - 1
    ans = n

    while low <= high:
        mid = (low + high) // 2
        # maybe an answer
        if arr[mid] > x:

            # look for smaller index on the left
            high = mid - 1
        else:
            ans = mid
            low = mid + 1  # look on the right

    return ans


if __name__ == "__main__":
    arr = [1, 2, 4, 7]
    x = 4
    ind = searchInsert(arr, x)
    print("The index is:", ind)

The index is: 2


In [5]:
arr = [3, 4, 4, 7, 8, 10]
n = 6
x = 5

floor, ceil = -1, -1
l, r = 0, len(arr) - 1
while l <= r:
    mid = l + (r - l) // 2
    if arr[mid] == x:
        floor, ceil = x, x
        break
    elif arr[mid] > x:
        ceil = arr[mid]
        r = mid - 1
    else:
        floor = arr[mid]
        l = mid + 1

print(floor, ceil)

4 7


In [12]:
arr = [3, 4, 13, 13, 13, 13, 20, 40]
t = 13
l, r = 0, len(arr) - 1
index = -1
while l <= r:
    mid = l + (r - l) // 2
    if arr[mid] < t:
        l = mid + 1
    else:
        if arr[mid] == t:
            index = mid
        r = mid - 1
index

2

In [21]:
arr = [1, 2, 3]


# every subsequence
def solve(arr, i, n, ds):
    if i >= n:
        print(ds)
        return

    ds.append(arr[i])
    solve(arr, i + 1, n, ds)
    ds.pop()
    solve(arr, i + 1, n, ds)


solve(arr, 0, 3, [])

[1, 2, 3]
[1, 2]
[1, 3]
[1]
[2, 3]
[2]
[3]
[]


In [25]:
# all subsequence  with sum k no duplicate
arr = [1, 2, 1]
k = 3


def solve(arr, i, n, k, ds):

    if k == 0:
        print(ds)
        return
    if i >= n:
        return
    if k >= arr[i]:
        ds.append(arr[i])
        solve(arr, i + 1, n, k - arr[i], ds)
        ds.pop()
    solve(arr, i + 1, n, k, ds)


solve(arr, 0, 3, 3, [])

[1, 2]
[2, 1]


In [1]:
# all subsequence  with sum k no duplicate
arr = [1, 2, 1]
k = 3


def solve(arr, i, n, k, ds):

    if k == 0:
        print(ds)
        return
    if i >= n:
        return
    for j in range(i, n):
        if k >= arr[j]:
            ds.append(arr[j])
            solve(arr, j + 1, n, k - arr[j], ds)
            ds.pop()
    # solve(arr, i + 1, n, k, ds)


solve(arr, 0, 3, 3, [])

[1, 2]
[2, 1]


In [13]:
# all subsequence  with sum k with duplicate
arr = [1, 2, 1]
k = 3


def solve(arr, i, n, k, ds):

    if k == 0:
        print(ds)
        return
    if i >= n:
        return
    if k >= arr[i]:
        ds.append(arr[i])
        solve(arr, i, n, k - arr[i], ds)
        ds.pop()
    solve(arr, i + 1, n, k, ds)


solve(arr, 0, 3, 3, [])

[1, 1, 1]
[1, 1, 1]
[1, 2]
[1, 1, 1]
[2, 1]
[1, 1, 1]


In [17]:
arr = [1, 2, 1]
k = 3


def solve(arr, i, n, k, ds):

    if k == 0:
        print(ds)
        return
    if i >= n:
        return
    if k >= arr[i]:
        ds.append(arr[i])
        solve(arr, i, n, k - arr[i], ds)
        ds.pop()
    while i < n - 1 and arr[i] == arr[i + 1]:
        i = i + 1
    solve(arr, i + 1, n, k, ds)


arr.sort()
solve(arr, 0, 3, 3, [])

[1, 1, 1]
[1, 2]


In [7]:
# can use this approch or remove duplicate directly inside recursion
arr.sort()
prev = arr[0]
temp = [arr[0]]
for i in range(1, len(arr)):
    if prev != arr[i]:
        temp.append(arr[i])
        prev = arr[i]
solve(temp, 0, len(temp), k, [])

[1, 1, 1]
[1, 2]


In [20]:
arr = [1, 2, 1]
k = 3
arr.sort()


def solve(arr, i, n, k, ds):

    if k == 0:
        print(ds)
        return
    if i >= n:
        return
    for j in range(i, n):
        if j != i and arr[j] == arr[j - 1]:
            continue
        if k >= arr[j]:

            ds.append(arr[j])
            solve(arr, j, n, k - arr[j], ds)
            ds.pop()
    # solve(arr, i + 1, n, k, ds)


solve(arr, 0, 3, 3, [])

[1, 1, 1]
[1, 1, 1]
[1, 1, 1]
[1, 2]
[1, 1, 1]
[1, 2]


In [9]:
def toString(List):
    return "".join(List)


# Function to print permutations of string
# This function takes three parameters:
# 1. String
# 2. Starting index of the string
# 3. Ending index of the string.


def permute(a, l, r):
    if l == r:
        print(toString(a))
    else:
        for i in range(l, r):
            a[l], a[i] = a[i], a[l]
            permute(a, l + 1, r)
            a[l], a[i] = a[i], a[l]  # backtrack


# Driver code
string = "ABC"
n = len(string)
a = list(string)

# Function call
permute(a, 0, n)

ABC
ACB
BAC
BCA
CBA
CAB


In [21]:
for i in range(5):
    if i % 2 == 0:
        continue
    print("ankit")

ankit
ankit


In [11]:
arr = [1, 0, 1, 1, 1, 1, 0, 0]
s = 0
for i in range(len(arr)):
    if arr[i] != 0:
        arr[s], arr[i] = arr[i], arr[s]
        s += 1
arr

[1, 1, 1, 1, 1, 0, 0, 0]

In [5]:
def findLongestSequence(A, k):

    left = 0  # represents the current window's starting index
    count = 0  # stores the total number of zeros in the current window
    window = 0  # stores the maximum number of continuous 1's found
    # so far (including `k` zeros)

    leftIndex = 0  # stores the left index of maximum window found so far

    # maintain a window `[left…right]` containing at most `k` zeros
    for right in range(len(A)):

        # if the current element is 0, increase the count of zeros in the
        # current window by 1
        if A[right] == 0:
            count = count + 1

        # the window becomes unstable if the total number of zeros in it becomes
        # more than `k`
        if count > k:
            while count > k:
                # if we have found zero, decrement the number of zeros in the
                # current window by 1
                if A[left] == 0:
                    count = count - 1

                # remove elements from the window's left side till the window
                # becomes stable again
                left = left + 1

        # when we reach here, window `[left…right]` contains at most
        # `k` zeros, and we update max window size and leftmost index
        # of the window
        if right - left + 1 > window:
            window = right - left + 1
            leftIndex = left

    # no sequence found
    if window == 0:
        return

    # print the maximum sequence of continuous 1's
    print(
        "The longest sequence has length",
        window,
        "from index",
        leftIndex,
        "to",
        (leftIndex + window - 1),
    )


if __name__ == "__main__":

    A = [1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0]
    k = 1

    findLongestSequence(A, k)

The longest sequence has length 7 from index 3 to 9


In [2]:
print("ank")

ank


In [3]:
arr = [0, 2, 0, 3, 0, 5, 6, 0, 0]
s = 0
for i in range(len(arr)):
    if arr[i] != 0:
        arr[s], arr[i] = arr[i], arr[s]
        s += 1
arr

[2, 3, 5, 6, 0, 0, 0, 0, 0]

In [3]:
import torch

In [ ]:
# if attention_mask is None:
#             attention_mask = torch.ones(((batch_size, seq_length + past_key_values_length)), device=device)

#         if token_type_ids is None:
#             if hasattr(self.embeddings, "token_type_ids"):
#                 buffered_token_type_ids = self.embeddings.token_type_ids[:, :seq_length]
#                 buffered_token_type_ids_expanded = buffered_token_type_ids.expand(batch_size, seq_length)
#                 token_type_ids = buffered_token_type_ids_expanded
#             else:
#                 token_type_ids = torch.zeros(input_shape, dtype=torch.long, device=device)

#         # We can provide a self-attention mask of dimensions [batch_size, from_seq_length, to_seq_length]
#         # ourselves in which case we just need to make it broadcastable to all heads.
#         extended_attention_mask: torch.Tensor = self.get_extended_attention_mask(attention_mask, input_shape)

#         # If a 2D or 3D attention mask is provided for the cross-attention
#         # we need to make broadcastable to [batch_size, num_heads, seq_length, seq_length]
#         if self.config.is_decoder and encoder_hidden_states is not None:
#             encoder_batch_size, encoder_sequence_length, _ = encoder_hidden_states.size()
#             encoder_hidden_shape = (encoder_batch_size, encoder_sequence_length)
#             if encoder_attention_mask is None:
#                 encoder_attention_mask = torch.ones(encoder_hidden_shape, device=device)
#             encoder_extended_attention_mask = self.invert_attention_mask(encoder_attention_mask)
#         else:
#             encoder_extended_attention_mask = None

In [1]:
def create_extended_attention_mask_for_decoder(
    input_ids, attention_mask: torch.Tensor = None, start_pos: int = 0
):
    device = input_ids.device
    batch_size, seq_length = input_ids.shape
    if attention_mask is None:
        attention_mask = (
            torch.ones(seq_length + start_pos).repeat(batch_size, 1).to(device)
        )
    seq_ids = torch.arange(seq_length).to(device)
    causal_mask = (
        seq_ids[None, None, :].repeat(batch_size, seq_length, 1)
        <= seq_ids[None, :, None]
    )

    causal_mask = causal_mask.to(attention_mask.dtype)

    if start_pos > 0:
        # torch.hstack(
        # [torch.zeros((seqlen, start_pos), device=input_ids.device), mask]
        causal_mask = torch.cat(
            [
                torch.ones(
                    (batch_size, seq_length, start_pos),
                    device=device,
                    dtype=causal_mask.dtype,
                ),
                causal_mask,
            ],
            axis=-1,
        )

    extended_attention_mask = (
        causal_mask[:, None, :, :] * attention_mask[:, None, None, :]
    )
    # extended_attention_mask = extended_attention_mask.to(
    #     dtype=dtype
    # )  # fp16 compatibility
    extended_attention_mask = (1.0 - extended_attention_mask) * torch.finfo(
        torch.float
    ).min

In [4]:
attention_mask = torch.tensor([[1, 1, 1, 0, 0], [1, 1, 1, 1, 0]])
# if self.config.is_decoder and encoder_hidden_states is not None:
# #             encoder_batch_size, encoder_sequence_length, _ = encoder_hidden_states.size()
# #             encoder_hidden_shape = (encoder_batch_size, encoder_sequence_length)
# #             if encoder_attention_mask is None:
# #                 encoder_attention_mask = torch.ones(encoder_hidden_shape, device=device)
# #             encoder_extended_attention_mask = self.invert_attention_mask(encoder_attention_mask)

In [5]:
create_extended_attention_mask_for_decoder(input_ids=attention_mask, start_pos=2)

In [6]:
attention_mask

tensor([[1, 1, 1, 0, 0],
        [1, 1, 1, 1, 0]])

In [6]:
attention_mask[None, :].size()

torch.Size([1, 2, 5])

In [7]:
seq_length = 5

In [8]:
seq_ids = torch.arange(seq_length)
seq_ids

tensor([0, 1, 2, 3, 4])

In [9]:
seq_ids[None, None, :].repeat(2, seq_length, 1).size()

torch.Size([2, 5, 5])

In [10]:
# seq_ids = torch.arange(seq_length)
causal_mask = seq_ids[None, None, :].repeat(2, seq_length, 1) <= seq_ids[None, :, None]

In [12]:
causal_mask.to(attention_mask.dtype)

tensor([[[1, 0, 0, 0, 0],
         [1, 1, 0, 0, 0],
         [1, 1, 1, 0, 0],
         [1, 1, 1, 1, 0],
         [1, 1, 1, 1, 1]],

        [[1, 0, 0, 0, 0],
         [1, 1, 0, 0, 0],
         [1, 1, 1, 0, 0],
         [1, 1, 1, 1, 0],
         [1, 1, 1, 1, 1]]])

In [42]:
seqlen = 5
start_pos = 0
mask = torch.full((seqlen, seqlen), 1)

mask = torch.triu(mask, diagonal=1)

# When performing key-value caching, we compute the attention scores
# only for the new sequence. Thus, the matrix of scores is of size
# (seqlen, cache_len + seqlen), and the only masked entries are (i, j) for
# j > cache_len + i, since row i corresponds to token cache_len + i.
mask = torch.hstack([torch.zeros((seqlen, start_pos)), mask])
mask

tensor([[0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0.]])

In [22]:
torch.ones(5).repeat(2, 1)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [1]:
def search_in_bitonic_array(arr, target):
    """
    Searches for a target element in a bitonic array.

    Args:
        arr: A bitonic array.
        target: The target element to search for.

    Returns:
        The index of the target element in the array, or -1 if the target element is not found.
    """

    left = 0
    right = len(arr) - 1

    while left <= right:
        mid = (left + right) // 2

        if arr[mid] == target:
            return mid

        elif arr[mid] > target:
            if arr[mid] > arr[mid + 1]:
                right = mid - 1
            else:
                left = mid + 1
        else:
            if arr[mid] < arr[mid - 1]:
                right = mid - 1
            else:
                left = mid + 1

    return -1


# Example usage:

arr = [1, 3, 5, 7, 9, 10, 8, 6, 4, 2]
target = 5

index = search_in_bitonic_array(arr, target)

if index != -1:
    print("The target element is at index", index)
else:
    print("The target element is not found in the array")

The target element is not found in the array


In [5]:
def findPeakElement(nums):
    if len(nums) == 1:
        return 0
    l, r = 0, len(nums) - 1
    while l <= r:
        mid = l + (r - l) // 2
        if (
            (mid == 0 and nums[mid] >= nums[mid + 1])
            or (mid == len(nums) - 1 and nums[mid - 1] <= nums[mid])
            or (
                mid < len(nums) - 1
                and mid > 0
                and nums[mid - 1] <= nums[mid]
                and nums[mid] >= nums[mid + 1]
            )
        ):
            return mid
        if mid - 1 >= 0 and nums[mid - 1] > nums[mid]:
            r = mid - 1
        else:
            l = mid + 1
    return 0

In [7]:
# arr = [1, 3, 5, 7, 9, 10, 8, 6, 4, 2]
arr = [1, 3, 50, 10, 9, 7, 6]
findPeakElement(arr)

2

In [8]:
def insertionSort(arr):

    # Traverse through 1 to len(arr)
    for i in range(1, len(arr)):

        key = arr[i]

        # Move elements of arr[0..i-1], that are
        # greater than key, to one position ahead
        # of their current position
        j = i - 1
        while j >= 0 and key < arr[j]:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key
        print(arr)


# Driver code to test above
arr = [12, 11, 13, 5, 6]
insertionSort(arr)
# for i in range(len(arr)):
#     print ("% d" % arr[i])

[11, 12, 13, 5, 6]
[11, 12, 13, 5, 6]
[5, 11, 12, 13, 6]
[5, 6, 11, 12, 13]


In [42]:
from collections import defaultdict, OrderedDict

# Sort by Frequency


def sortByFreq(arr, n):
    # arr -> Array to be sorted
    # n   -> Length of Array

    # d is a hashmap(referred as dictionary in python)
    d = defaultdict(lambda: 0)
    for i in range(n):
        d[arr[i]] += 1
    print(d)

    # Sorting the array 'arr' where key
    # is the function based on which
    # the array is sorted
    # While sorting we want to give
    # first priority to Frequency
    # Then to value of item
    arr.sort(key=lambda x: (d[x], x), reverse=True)
    # require Updation:- reverse = True, to sort an array in descending order (Jayesh Verma)
    return arr


# Driver code
if __name__ == "__main__":
    arr = [2, 5, 2, 6, -1, 9999999, 5, 8, 8, 8]
    n = len(arr)

    # Function call
    solution = sortByFreq(arr, n)
    print(*solution)

defaultdict(<function sortByFreq.<locals>.<lambda> at 0x000001FFB0927B00>, {2: 2, 5: 2, 6: 1, -1: 1, 9999999: 1, 8: 3})
8 8 8 5 5 2 2 9999999 6 -1


In [28]:
class Student:
    def __init__(self, name, grade, age):
        self.name = name
        self.grade = grade
        self.age = age

    def __repr__(self):
        return repr((self.name, self.grade, self.age))


student_objects = [
    Student("john", "A", 15),
    Student("jane", "B", 12),
    Student("dave", "B", 10),
    Student("abc", "A", 12),
    Student("ab", "A", 15),
    Student("ac", "A", 16),
]

In [31]:
import functools


def mycmp(a, b):
    # print("comparing ", a, " and ", b)
    if a.age > b.age:
        return 1
    elif a.age < b.age:
        return -1
    else:
        if len(a.name) < len(b.name):
            return -1
        return 1


print(sorted(student_objects, key=functools.cmp_to_key(mycmp)))

[('dave', 'B', 10), ('abc', 'A', 12), ('jane', 'B', 12), ('ab', 'A', 15), ('john', 'A', 15), ('ac', 'A', 16)]


In [49]:
d = dict()
for i in range(n):
    if arr[i] in d:
        d[arr[i]][0] += 1
    else:
        d[arr[i]] = [1, i]
arr = [2, 5, 2, 6, -1, 9999999, 5, 8, 8, 8]

In [50]:
d

{2: [2, 0], 5: [2, 1], 6: [1, 3], -1: [1, 4], 9999999: [1, 5], 8: [3, 7]}

In [53]:
def compare(a, b):
    if d[a][0] > d[b][0]:
        return -1
    elif d[a][0] < d[b][0]:
        return 1
    else:
        if d[a][1] > d[b][1]:
            return 1
        return -1

In [54]:
sorted(arr, key=functools.cmp_to_key(compare))

[8, 8, 8, 2, 2, 5, 5, 6, -1, 9999999]

In [55]:
# Python3 implementation of QuickSort


# Function to find the partition position
def partition(array, low, high):

    # Choose the rightmost element as pivot
    pivot = array[high]

    # Pointer for greater element
    i = low - 1

    # Traverse through all elements
    # compare each element with pivot
    for j in range(low, high):
        if array[j] <= pivot:

            # If element smaller than pivot is found
            # swap it with the greater element pointed by i
            i = i + 1

            # Swapping element at i with element at j
            (array[i], array[j]) = (array[j], array[i])

    # Swap the pivot element with
    # the greater element specified by i
    (array[i + 1], array[high]) = (array[high], array[i + 1])

    # Return the position from where partition is done
    return i + 1


# Function to perform quicksort
def quicksort(array, low, high):
    if low < high:

        # Find pivot element such that
        # element smaller than pivot are on the left
        # element greater than pivot are on the right
        pi = partition(array, low, high)

        # Recursive call on the left of pivot
        quicksort(array, low, pi - 1)

        # Recursive call on the right of pivot
        quicksort(array, pi + 1, high)


# Driver code
if __name__ == "__main__":
    array = [10, 7, 8, 9, 1, 5]
    N = len(array)

    # Function call
    quicksort(array, 0, N - 1)
    print("Sorted array:")
    for x in array:
        print(x, end=" ")

Sorted array:
1 5 7 8 9 10 

In [56]:
# Python program for implementation of Selection
# Sort
A = [64, 25, 12, 22, 11]

# Traverse through all array elements
for i in range(len(A) - 1):

    # Find the minimum element in remaining
    # unsorted array
    min_idx = i
    for j in range(i + 1, len(A)):
        if A[min_idx] > A[j]:
            min_idx = j

    # Swap the found minimum element with
    # the first element
    A[i], A[min_idx] = A[min_idx], A[i]

# Driver code to test above
print("Sorted array")
for i in range(len(A)):
    print(A[i], end=" ")

Sorted array
11 12 22 25 64 

In [57]:
# Optimized Python program for implementation of Bubble Sort


def bubbleSort(arr):
    n = len(arr)

    # Traverse through all array elements
    for i in range(n):
        swapped = False

        # Last i elements are already in place
        for j in range(0, n - i - 1):

            # Traverse the array from 0 to n-i-1
            # Swap if the element found is greater
            # than the next element
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
                swapped = True
        if swapped == False:
            break


# Driver code to test above
if __name__ == "__main__":
    arr = [64, 34, 25, 12, 22, 11, 90]

    bubbleSort(arr)

    print("Sorted array:")
    for i in range(len(arr)):
        print("%d" % arr[i], end=" ")

# This code is modified by Suraj krushna Yadav

Sorted array:
11 12 22 25 34 64 90 

In [58]:
# Python program for implementation of Insertion Sort


# Function to do insertion sort
def insertionSort(arr):

    # Traverse through 1 to len(arr)
    for i in range(1, len(arr)):

        key = arr[i]

        # Move elements of arr[0..i-1], that are
        # greater than key, to one position ahead
        # of their current position
        j = i - 1
        while j >= 0 and key < arr[j]:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key


# Driver code to test above
arr = [12, 11, 13, 5, 6]
insertionSort(arr)
for i in range(len(arr)):
    print("% d" % arr[i])

# This code is contributed by Mohit Kumra

 5
 6
 11
 12
 13


In [59]:
# Python program for implementation of MergeSort


def merge(arr1, arr2):
    i = 0
    j = 0
    result = []
    while i < len(arr1) and j < len(arr2):
        if arr2[j] > arr1[i]:
            result.append(arr1[i])
            i += 1
        else:
            result.append(arr2[j])
            j += 1
    while i < len(arr1):
        result.append(arr1[i])
        i += 1
    while j < len(arr2):
        result.append(arr2[j])
        j += 1

    return result


def mergeSort(arr):
    if len(arr) <= 1:
        return arr
    mid = len(arr) // 2
    left = mergeSort(arr[:mid])
    right = mergeSort(arr[mid:])

    return merge(left, right)


# Driver Code
if __name__ == "__main__":
    arr = [12, 11, 13, 5, 6, 7]
    print("Given array is")
    print(*arr)
    arr = mergeSort(arr)
    print("\nSorted array is ")
    print(*arr)

# This code is contributed by Vishu Vaishnav

Given array is
12 11 13 5 6 7

Sorted array is 
5 6 7 11 12 13
